server.port=9999
spring.application.name=openai
logging.pattern.console=%d{HH:mm:ss} %clr(%-5level) [%15.15thread] %clr(%-40.40logger{39}){cyan} : %msg%n
spring.ai.openai.api-key=${OPENAI_KEY}
spring.ai.ollama.chat.options.model=llama3.2:1b
spring.ai.ollama.base-url=http://localhost:11434
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# vector store embedding model to choose
#spring.ai.openai.embedding.options.model=text-embedding-3-small


spring.datasource.url=jdbc:h2:file:~/chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=andrey
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

#stops containers in the project but do not remove the volume
spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=eazybytes
